### ISSUE TITLE
Handwraps and unarmed strikes dont seem to work

### ISSUE THREAD

**Issue by GuitarGuyNick** [Saibot393/enhancedcombathud-pf2e#1]
when you drag unarmed strikes onto the weapons. handwraps doesnt seem to send out a roll.

**Comment by Saibot393** [comment]
Unarmed strikes (and other actions) can now be dragged into weapon slots with v1.0.1

**Comment by Saibot393** [comment]
Strikes should now correctly work with v1.1.0
