### ISSUE TITLE
Request: Actions (runs BAM from Workbench)

### ISSUE THREAD

**Issue by apoapostolov** [Saibot393/enhancedcombathud-pf2e#10]
BAM (Basic Action Macro) is one of the most important macros that come with Workbench. It gives the players an entry to run every action check in the game, from Shove to Decypher Text. 

An option that when turned on will add a big or small block for Actions to run the macro would get the players to run BAM in combat without access to the macro bar.

**Comment by Saibot393** [comment]
An option to use macros from the GX UD is planned

**Comment by Saibot393** [comment]
Macro buttons have been added with v1.3.0
