### ISSUE TITLE
Kineticist Elemental Blast Support

### ISSUE THREAD

**Issue by Legilas** [Saibot393/enhancedcombathud-pf2e#11]
Hi there! 

I've been testing your module and love the pf2e support so far. My pal plays a Kineticist and had some issues with the usage of Elemental Blasts. We can drag and drop the Elemental Blasts into the weapon set as described in the changelogs of version 1.1.0, the problem is that the Blasts then do not have options for an attack roll, MAPs and the such. Only the info card about the general action is printed to the chat. Also, no toggles for a melee or ranged blast are available or switches for damage types, which can be used given the right feats. 

Am I missing something, or is this indeed a feature that is not yet implemented or cannot be implemented due to its complexity?
![elemental_blast](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/6b41547d-a2f8-4e47-8617-973b0afb73e2)

**Comment by Legilas** [comment]
Alright, interesting, I thought to have done it correctly. Maybe another screenshot: I dragged and dropped these two, which Action are you referring to?
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/8a661dc4-fa4b-464a-b999-4de28724e696)

**Comment by Saibot393** [comment]
Those should work, are there any errors in the console (F12)?

**Comment by Legilas** [comment]
Indeed there is an error, but it only seems to be a notification of a deprecated function:

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/3f2092b7-de98-4026-b2c6-3eb1527a3ae6)

**Comment by Legilas** [comment]
Hm, tracking back in the log, there is also the following uncaught exception when opening the HUD through the left sidebar:

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/810e33b1-a207-49ba-935c-52031a3c1458)

**Comment by Legilas** [comment]
I also tested the air elemental blast that you gave as a visual example and it still does not seem to work, so its not tied to the different type of blast :/

**Comment by Saibot393** [comment]
Which version of the module are you running?

**Comment by Legilas** [comment]
Very interesting, its the 1.0.1 version, your hunch is correct. As I just now installed the module I simply assumed it would be the most recent version. Looks as though I was mistaken in that assumption. I'll install the new version right now. Gosh, not coming up with this myself is quite embarassing. Thanks for your time regardless. ^^

**Comment by Saibot393** [comment]
no problem, out of interest, are you using forge?

**Comment by Legilas** [comment]
No, I'm self hosting my server on a raspberry pi.

**Comment by Saibot393** [comment]
Hmm, interesting, forge would have explaned it

**Comment by Legilas** [comment]
Ok, now it gets weird. I updated the version, now version 1.1.2, and I still have the same issue. Even created a new character to make absolutely sure its not tied to old data. Maybe I'm still missing a step or two, so I'll list all the steps I took:

1. Selected the Kineticist
2. Opened the HUD
3. Use Channel Elements to activate the aura and create the specific blast attacks in the sheet
4. Drag and drop the created Blast Actions into the weapon set 
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/c074e9d5-7cb2-4758-b7cc-45de272a9f7e)

5. I get this generic elemental blast as in the screenshot without attack rolls and all. Now with an icon for whatever reason though.

**Comment by Saibot393** [comment]
Do you have any modules installed that could interfere with kineticist actions?

**Comment by Legilas** [comment]
Just now, I simply deactivated all modules except the HUD, no change sadly. I recently updated the PF2e system to its newest version (5.13.4) and the Foundry version is version 11.315.

**Comment by Saibot393** [comment]
Could you enter this into the console, then drag the blast on the weapon set and send me the output: `ui.ARGON.components.weaponSets._onDrop = (event) => {console.log(JSON.parse(event.dataTransfer.getData("text/plain")))}`
The ouputs should (after unfolding it) look a little like this: 
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/137942782/d524d10d-c277-46f0-877c-6769e46db824)

**Comment by Legilas** [comment]
Gladly, the output is the following:
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/1110e470-bc48-434d-9381-efa8aa11cfda)

**Comment by Saibot393** [comment]
could you send me your world file (without the media data)?

**Comment by Legilas** [comment]
Could you specify which specific file that is? I'm currently in the data folder of my world and there is a substantial amount of files. Are we talking of simply the entire folder minus assets or a specific file?

**Comment by Saibot393** [comment]
yes, the entire folder without the assets

**Comment by Legilas** [comment]
[Bugworld.zip](https://github.com/Saibot393/enhancedcombathud-pf2e/files/14215700/Bugworld.zip)
Alright, hope thats all you require.

**Comment by Saibot393** [comment]
Looks right on first glance, thank you. I will take a look at it tomorrow

**Comment by Saibot393** [comment]
Now its getting truly strange, when i use "Yor" to drag the blasts into the weapon sets, the blast is set up correctly:
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/137942782/b11675a3-4c84-45c5-a337-592d74f4dd95)
Which browser are you using?
I have released special debug version that can be manually installed via this link: https://github.com/Saibot393/enhancedcombathud-pf2e/releases/download/debug1/module.json
It will output some info into the console when an item is dragged into the weapon set, could you drag the blast into it again and send me the output, it should look something like this (possible longer):
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/137942782/52b8b57b-ffd5-4fbe-a2c2-43800b13e623)

**Comment by Legilas** [comment]
Now, I'll be... It works. I sleep over it, and it works. How? xD

I díd not restart the server, I didn't even restart the world, the server should in theory be in the very same state I left it yesterday. And yet... wtf. Ok, whatever, I'll not let myself be gaslighted by Foundry, Issue closed, this time for good. Thank you for your patience. :)
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/19415090/d6927e1c-7217-41f5-91fd-92625237441b)

...
But seriously, how.

**Comment by Saibot393** [comment]
Foundry taketh, foundry giveth, at least its solved now

**Comment by Legilas** [comment]
Amen.
