### ISSUE TITLE
Grip changing on weapon and causing two handed weapons to appear as unequipped

### ISSUE THREAD

**Issue by mkniller** [Saibot393/enhancedcombathud-pf2e#12]
After the update to version v1.1.3 I found that dragging weapons to the slots above the character portrait is changing the grip on the weapon.

In my case, my player has a arbalest, a two handed crossbow.  When I drag that on the HUD it changes to a one handed weapon, and then is technically unequipped.  The PF2E Ranged Combat module is not letting my player attack.  I have to go into my character sheet and re-enable 2 hands.

Foundry v11 build 315
Module version v1.1.3
Argon Core version 2.5.5
Browser: Chrome

**Comment by mkniller** [comment]
I think I misunderstood how those boxes work.  I dropped two arbalets in the first two boxes and it used the correct grip...

If that is the correct behavior, please close this.

**Comment by Saibot393** [comment]
Yes, the intend is to have the slots in which the item is equiped equal the hands with which the items is held

**Comment by mkniller** [comment]
Got it.  That wasn't 100% clear at first, but It makes total sense now!

**Comment by Saibot393** [comment]
Btw. the next version will include a setting to increase the number of item sets, in case the three are not enough, considering that two handed weapons take two slots
