### ISSUE TITLE
Kineticist Elemental Blast Permutations

### ISSUE THREAD

**Issue by XtremelyBadProgrammer** [Saibot393/enhancedcombathud-pf2e#13]
First of all, props for the module. It rules.

Elemental Blast is not working quite right with the various options. It's a very complicated attack that works weirdly compared to everything else on every other character sheet so this doesn't surprise me. Sorry about the length of this but I wanted to be very thorough with what I talked about.

The first thing that's not working correctly is the sync between the one-action and two-action toggle of Elemental Blast on the character sheet and the action HUD. On the character sheet is toggle that allows the PC to set the type of Elemental Blast to either One Action or Two Action.

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/141167463/54e77878-5ee1-4876-9998-f1baab794b0f)

The Argon HUD has no way to allow the character to choose between these two types of Blasts, and does not update when the types are changed from the character sheet. It will, however, update the blast type if the HUD is reloaded (clicking the crossed swords twice, once to unload and once to reload) or if the user toggles a different weapon set, then retoggles the weapon set with Elemental Blast. A quick fix would be to have the HUD to show a small one/two action icon on the Elemental Blast, maybe next to the Melee/Ranged Icon and the Damage Type Icon so that the user at least knows what Elemental Blast type they are getting if they click the attack and can refresh the HUD to get the other kind, if they want.

The second thing that's not working correctly is the interaction between the Feat Versatile Blast and Elemental Blast. This feat allows the character to select different damage types for their Elemental Blast, depending on what type of Elemental Gate(s) they have. There's a small icon on the HUD that allows the user to toggle between the damage types that the Versatile Blast provides. The issue is, for elements like Earth, it only picks up 2 of the 3 damage types. It will show Bludgeoning and Piercing, but not Poison. For things like Fire, that has only Cold and Fire types, it works great. For elements with 3 damage types, it only has two, and it always seems to be the two leftmost buttons damage types from the Character Sheet.

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/141167463/b36d861e-cadb-46fd-9058-88034d4df97c)

The last is Weapon Infusion. This is getting picked up by the HUD and applies successfully when clicked, however when the effect is applied to the Kineticist PC they get a bunch more options for their Elemental Blast on their character sheet. 

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/141167463/b5f81e07-af03-483a-8804-e6a5250006e7)

They get two new dropdowns that allow them to choose "Infusions" for both their Melee and Ranged blast. These Infusions add traits to the attack like Volley, Reach, etc. None of these are accessible from the HUB. It does look like they get applied from the character sheet if the HUD is reloaded or the weapon set is selected/deselected, but there's some strangeness. For instance, the Range of the attack is six times larger than it should be when Thrown, Propulsive, or Volley is selected (these are ranges of 20ft, 50ft and 100 ft but are shows as 120ft, 300ft and 600ft). The different damage types that can be selected from the HUD are still set at only 2, so the new damage types granted by Weapon Infusion either overwrite one of the base damage types (for Fire you can only select Bludgeoning and Cold). So there's some weirdness going on with the traits that Weapon Infusion grants.

Ok that's it for me! Sorry to be longwinded, thank you again for this great HUD!

**Comment by Saibot393** [comment]
Thank you for the detailed description, this will help me alot with fixing the blasts.
Also, glad you enjoy the module

**Comment by Saibot393** [comment]
v1.2.2 should fix the problems:
- Action number could already be chosen under "toggles (see screenshot)", now the tooltips should update correctly
- It should now be possible to correctly toggle the damage options from Versatile Blast
- Weapon Infusion should now also work correctly, the damage type should be choosable, and the toggles should add the correct range and traits to the tooltip. The toggles them selfs can be changed via the menu point toggles (see screenshot)

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/137942782/7e2b518d-914e-4cbd-be8b-92016ac8855f)

I hope i fixed all the issues you mentioned, if something still doesn't work or there are more things, feel free to reopen this issue or make a new one, thanks again for the datailed description, hepled alot with fixing
