### ISSUE TITLE
change the image by the number of possible actions

### ISSUE THREAD

**Issue by medeiros961030** [Saibot393/enhancedcombathud-pf2e#16]
It would be interesting to show the number of actions needed to execute in the actions tab, and not the photo below itself

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/112792783/2cdb10b3-4854-4206-ad69-f26fd9a7756a)

**Comment by Saibot393** [comment]
Do you mean something like a small symbol on the item/feat buttons? If so i will add add in one of the next updates.

**Comment by Saibot393** [comment]
So i assume that the setting "Show actions requirements" solves this issue
