### ISSUE TITLE
feature request: swap function.

### ISSUE THREAD

**Issue by GuitarGuyNick** [Saibot393/enhancedcombathud-pf2e#2]
it would be cool if there was a small swap button next to the weapons to use the remaster swap action. 
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/139762764/44f9ae64-1d0a-4459-80bc-fe80ee8f3524)
 so that you could select consumables and replace what is in your hands.

**Comment by Saibot393** [comment]
I will look into that

**Comment by Saibot393** [comment]
An option to display a "swap" icon for holdable items has been added ith v1.2.0
