### ISSUE TITLE
Request: Additional Attack Effects

### ISSUE THREAD

**Issue by sejrsgaard** [Saibot393/enhancedcombathud-pf2e#26]
Would it be possible to include the **Additional Attack Effects** in the attack popout?

When looking at attacks in the character sheet I always use the effects noted beside traits to refer to additional effects, in this case **Grab** and **Burn Eyes**.
<img width="472" alt="image" src="https://github.com/Saibot393/enhancedcombathud-pf2e/assets/5079192/3ec131ea-8ba5-410e-a9ae-931bd2008ea2">
<img width="470" alt="image" src="https://github.com/Saibot393/enhancedcombathud-pf2e/assets/5079192/84badd2c-a714-48fb-91b5-e668db8f9155">

It would be great if these would also show in the popouts for the attacks as a quick way of determining additional effects
<img width="290" alt="image" src="https://github.com/Saibot393/enhancedcombathud-pf2e/assets/5079192/bba85995-36fa-4841-ab6e-8d74177c0def">
<img width="312" alt="image" src="https://github.com/Saibot393/enhancedcombathud-pf2e/assets/5079192/818954f6-30e9-4e8f-ae36-5bf3e8fea29b">

**Comment by Saibot393** [comment]
Yes, that seems usefull, i will look into it.

**Comment by Saibot393** [comment]
The effects should now be displayed in the tooltips with v1.10.0. In addition there is also a setting to show small icons for the connected passives in the item button

**Comment by ksj-trackunit** [comment]
That is absolutely awesome. Thanks for such a great addon 🙏
