### ISSUE TITLE
Request : French support

### ISSUE THREAD

**Issue by Araluen124** [Saibot393/enhancedcombathud-pf2e#27]
Hi, if possible, i would like to see the HUD in french
I do not know how to do a json like the polish guy but there is the link to the french translation of the system if it helps
https://gitlab.com/pathfinder-fr/foundryvtt-pathfinder2-fr

**Comment by Araluen124** [comment]
Nevermind, apparently the system translation translates everything

**Comment by Saibot393** [comment]
Outside of the module settings there are a few details that are not translated via the system translation (e.g. the button name for "refocus" or the "accept"/"abbort" buttons for some popups). If you are still interested in translating it (which is relatively easy) let me know and i can walk you through it
