### ISSUE TITLE
Argon Combat HUD - Players should not see HUD on defeated creatures

### ISSUE THREAD

**Issue by DoritoBob** [Saibot393/enhancedcombathud-pf2e#29]
When characters select a defeated creature after an encounter, they can see the HUD, which gives away everything about the creature.  One of my players, right after a combat encounter when they were going to collect loot, selected the defeated creature and told me the Argon Combat HUD displayed for him for that creature.  This occurs even with all other modules turned off. 

Solution: Players should only gain Argon Combat HUD access to tokens they actually own.

**Comment by Saibot393** [comment]
i have a PR pending in the CORE module, i will close this issue once the PR has been merged.

**Comment by DoritoBob** [comment]
thank you

**Comment by Saibot393** [comment]
The bug should now be solved wtih v1.8.1 (the CORE PR was denied)
