### ISSUE TITLE
 api to use argon hud actions

### ISSUE THREAD

**Issue by bb46003** [Saibot393/enhancedcombathud-pf2e#32]
Hi when you add this part  game.modules.get("enhancedcombathud-pf2e").api.useAction(actiontype, actionamount)) to Macro and HUD is turn off macro is falling because  HUD didn’t have information about actor. Can you add if condition to check if HUD is on and if yes is run rest of script and if not it ignore.

**Comment by Saibot393** [comment]
yes, thats an oversight, i will add it with the next version

**Comment by Saibot393** [comment]
The bug should be solved with v1.8.2
