### ISSUE TITLE
Ammunition Drop Bar is Difficult to Use

### ISSUE THREAD

**Issue by populusswarm** [Saibot393/enhancedcombathud-pf2e#33]
Thanks for the great work first of all.

I find the ammunition bar on the ranged weapon difficult to use. If I move the cursor out of the range of the weapon icon, the ammunition drop down bar will disappear, so I have to use arrow keys to switch weapon. The bar itself is quite small and can not be scaled in setting, unlike the change grip or reload button (if using ranged combat mod), so it is easy to click at the upper half of the bar, and the drop box will be there for only one second and then disappear. Not sure this issue only applies to me or everyone else.

My own solution is using switch ammunition macro from PF2e Ranged Combat first and click reload on the weapon icon, so I can do it all with my mouse, no arrow keys involved. Thus I think it is a good idea to allow ranged combat users to customize their ranged weapon icon as "switch ammunition" "reload" "change grip" instead of "ammunition bar" "reload" "change grip". It would still be struggling for users who do not use ranged combat though, if they are experiencing the same issue.

<img width="408" alt="Screenshot 2024-02-20 200357" src="https://github.com/Saibot393/enhancedcombathud-pf2e/assets/114119905/79c91c2c-aa17-45b4-a7b1-89b705af0c6f">

**Comment by Saibot393** [comment]
Yeah, dropdowns have been a problem for a couple of users, i haven't found a good solution yet. Using the switch ammunition macro as an option is a good idea for this case though, i will add it in one of the next updates.

**Comment by Saibot393** [comment]
I have added an option to use the ammo swap macro instead of the select with v1.9.0
