### ISSUE TITLE
Request: Stamina Variant Rules

### ISSUE THREAD

**Issue by droideck** [Saibot393/enhancedcombathud-pf2e#36]
I'm not sure how hard it will be to implement, but it will be great to have Stamina values displayed alongside HP. 
https://2e.aonprd.com/Rules.aspx?ID=1378
Also, there are a few ways to restore it: Take a Breather exploration activity and Steel Your Resolve action.

I think these three options will be a nice minimum implementation for the system:
- Stamina points;
- Take a Breather exploration activity;
- Steel Your Resolve action.

Thank you!

P.S. Stamina variant rules can be enabled as a Variant Rule in PF2e system settings.

**Comment by Saibot393** [comment]
Adding stamina points should be easy enough, i planned on improving the out of combat actions anway, so adding "Take a Breather" would fit right in and the "Steel Your Resolve" action as a conditional action should also be easy enought to do, i will look into it in one of the next updates

**Comment by Saibot393** [comment]
I have added support for the stamina system with v1.10.0
