### ISSUE TITLE
2H weapons changing grip automatically

### ISSUE THREAD

**Issue by Kronos25** [Saibot393/enhancedcombathud-pf2e#39]
Hey!

One of my players reported that everytime he changed the grip of his sword (katana) to 2h, a couple of seconds later it auto-changed to 1h. I'm not 100% sure if this is something others have noticed, but it started when I implemented this module.

**Comment by Saibot393** [comment]
Does the player have the Katana in a weapon set?

**Comment by Kronos25** [comment]
Yes, they do! Here are a couple of screens:
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/25178802/f9c30346-558d-477c-bb8b-a5e3a5e4aa36)
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/25178802/6fcb74b6-d814-47c6-9fb4-02c3fc70871a)

Clicking to change to 2h:
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/25178802/3c3abff6-9413-4d9a-98aa-018cc3b99385)

If I click outside of the token or to another token, it changes back to 1h:
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/25178802/ffae268d-5e78-42b2-a361-c30ee169f602)

Same behaviour happens when changing directly from the sheet (change to 2h and after that if I click on something else, it changes to 1h).

**Comment by Saibot393** [comment]
Ah, ok. What happens is the following: When you click on the item set again, it will "reapply" the weapon set. Since the weapon is only one handed in the weaponset it will revert to that state. I will look into changing that

**Comment by Saibot393** [comment]
Should now be fixed with v1.10.3
