### ISSUE TITLE
intiative could have a drop down menu before rolling.

### ISSUE THREAD

**Issue by GuitarGuyNick** [Saibot393/enhancedcombathud-pf2e#4]
sorry if theres alot of things i was just so excited now there is an argon hud mod for pf2. glad to have it anyway. 

my suggestion for an improvement is that when you click the intiative button. a pop up in the center of the screen with a drop down box would be useful for selecting which skill before going into initative.

or shift click to bypass and default to perception.

**Comment by Saibot393** [comment]
I will look into something like this

**Comment by Saibot393** [comment]
I have added an initiative menu with v1.1.0 (it will show up in the portrait when relevant)
