### ISSUE TITLE
Request: Saving Throws

### ISSUE THREAD

**Issue by Bryan-Legend** [Saibot393/enhancedcombathud-pf2e#41]
Could you please not bury the saving throws under a menu? Hitting them fast is important to me. Maybe bury the rest buttons under the  menu instead.

As a GM I sometimes have to make 10 saving throws at once for a group of enemies, any chance you could get that working? It works in the Action Bar module and that's keeping me from switching.

**Comment by Saibot393** [comment]
There is a setting called "Show saving throws in portrait" that causes small icons for the saves to show up in the portrait
![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/137942782/4a8da501-3621-4f50-9dc3-e83780734cd6)

**Comment by Bryan-Legend** [comment]
Very cool. Maybe default it to on? I'd never have found it.

**Comment by Saibot393** [comment]
I like to keep the default settings as close to the default Argon design as possible. Though i agree that the settings have become a bit much. Not sure hoew to solve that though, if i am honest.

**Comment by Bryan-Legend** [comment]
I feel your pain. I know it's tricky but I'd recommend removing the setting
to simplify.

**Comment by Bryan-Legend** [comment]
♥️
