### ISSUE TITLE
Missing Core skills from NPC HUD

### ISSUE THREAD

**Issue by LastAtlantean** [Saibot393/enhancedcombathud-pf2e#44]
As seen in the below picture, there are no skills to roll like there are for PC sheets. I recall seeing them in the past, but with the update I did today (PF2e Combat HUD v. 1.11.3) (PF2e v. 5.15.0) they are not present on NPCs.

![image](https://github.com/Saibot393/enhancedcombathud-pf2e/assets/85305985/b13fa778-569a-4e5b-a28b-da09d90fb050)

**Comment by Saibot393** [comment]
Only skill that are explicitly present in the NPC sheet are displayed in the HUD. Though i plan on adding a setting soon, that allows all NPC skills to be displayed

**Comment by LastAtlantean** [comment]
I suppose I should've been clearer; there are skills on the NPC sheet and none of them appear on the HUD.

**Comment by Saibot393** [comment]
It appears, that one of the recent Pf2e updates changed the way NPC skill work, should now be fixed with v1.11.4

**Comment by LastAtlantean** [comment]
Just updated and it's fixed! Thank you!
