### ISSUE TITLE
Allow changing versatile damage types

### ISSUE THREAD

**Issue by DamianLyszczarczyk** [Saibot393/enhancedcombathud-pf2e#56]
In the HUD there is an icon on the weapon that corresponds to the damage type of the weapon and says it's a versatile type however there is no way to change that versatile type for example clicking on the icon. You need to go to your character sheet and change it there for the HUD to register that change.
![image](https://github.com/user-attachments/assets/52d31044-74ca-4d5a-9412-bcbcd8f3d6d2)
![image](https://github.com/user-attachments/assets/2b6faca6-af80-43e3-ba34-f8cad9673b50)
Would be a nice QoL change if it could be toggleable within weapon in the HUD

**Comment by Saibot393** [comment]
That should actually already be possible. Maybe a recent update to the system changed something and broke my code. I will investigate

**Comment by Saibot393** [comment]
The bug should now be fixed with v2.0.2

**Comment by DamianLyszczarczyk** [comment]
Just tested it and it works correctly, thanks!
