### ISSUE TITLE
Installing Enhanced Combat HUD PF2e also installs DnD5e module

### ISSUE THREAD

**Issue by robinsving** [Saibot393/enhancedcombathud-pf2e#58]
For some reason, Dnd5e is marked as a recommendation for the CORE module. This means that there will be a recommended installation for DnD5e when playing PF2e, which makes no sense.

If there is functionality from DnD5e which enhances the CORE, then why not put that in the CORE, so that we won't have to get this notification from Foundry VTT?

![image](https://github.com/user-attachments/assets/decbb5b1-a3f9-4d15-827b-1225014a3e8c)

**Comment by Saibot393** [comment]
The reason the D&D5e module is recommended is because originally CORE and D&D5e were one module and only split a few months ago. To prevent confusion over this change TheRipper decided to still recommend the D&D5e module. You can uninstall without it affecting anything.

**Comment by robinsving** [comment]
You'd hope that the users from DnD5 would be smarter than TheRipper thinks they are. But I guess we can close this ticket, and I'll create a ticket in the main repo
