### ISSUE TITLE
Ability buttons for Actions/Reactions/Free Actions not showing the correct label

### ISSUE THREAD

**Issue by OverlordSoS** [Saibot393/enhancedcombathud-pf2e#60]
![image](https://github.com/user-attachments/assets/2be8db38-7a3b-46b8-bfb6-3c5ca2b610b6)

See above, the label for the Abilities containers in Actions/Reactions/Free Actions is not showing up properly

**Comment by Saibot393** [comment]
That is curious, which browser are you using?

**Comment by OverlordSoS** [comment]
Firefox, but I have confirmed it is also happening in Chrome. It also happened for all players.

**Comment by Saibot393** [comment]
You are using the tin color theme, right? Could you send another screenshot with another background behind the bars e.g. the default foundry empty scene grey background? Also, does that only happen with the Pf2e module or also with other Argon modules like the D&D5e one?

**Comment by OverlordSoS** [comment]
Yeah, tin colour theme. Can confirm it also happens in the default colour theme.

![image](https://github.com/user-attachments/assets/ba11cd04-fa3f-4271-9ad0-28a5a89df7a2)
![image](https://github.com/user-attachments/assets/fa7d8dc1-3efb-4def-a34c-a4fc540dde9c)
![image](https://github.com/user-attachments/assets/8aea137a-ce5b-40c4-ad13-54017b9b11b4)

I'm not familiar with the 5e module, but I couldn't seem to recreate the issue in that module. Also, showed a picture of a NPC sheet token having the same issue

**Comment by Saibot393** [comment]
I think i misread/misunderstood what you meant, sorry. The action pips only show up for tokens that are in combat.

**Comment by Saibot393** [comment]
Sorry, i previously misread your issue description, my bad. The bug should be fixed with v2.0.5
